#spring:
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/big_event
#    username: root
#    password: root
#
#  data:
#    redis:
#      host: localhost
#      port: 6379
#
#mybatis:
#  configuration:
#    map-underscore-to-camel-case: true
#
#aliyun:
#  oss:
#    endpoint:
#    access-key-id:
#    access-key-secret:
#    bucket-name:
#knife4j:
#  enable: true
#  basic:
#    enable: true
#    base-package:
#
